### ISSUE TITLE
網址下載無法下載原圖

### ISSUE THREAD

**Issue by Raymond9487** [ken1882/EHDownloader#1]
如標題，target中的網址好像無法下載原圖。

**Comment by ken1882** [comment]
RTFM

**Comment by ken1882** [comment]
我剛剛想到可能是因為原圖檔案太大並且你網路速度過慢所導致，下個patch將加入自訂允許最慢下載時間

**Comment by Raymond9487** [comment]
再請教，如果用網址下載原圖是動config.txt嗎 感謝

**Comment by ken1882** [comment]
已於v0.1.5p1新增修改時限的選項，現在下載原圖的預設時限是30秒；對網速較慢的使用者可於`config.txt`中依自身網速自行修改時限
